project_id = "kjubpaflsffnioixbfec"

[functions.generate-summary]
verify_jwt = false

[functions.generate-quiz]
verify_jwt = false

[functions.analyze-image]
verify_jwt = false

[functions.send-telegram]
verify_jwt = false
