// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp, auth } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-platform-info.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_platform_info_default = defineTool({
  name: "get_platform_info",
  title: "Get platform info",
  description: "Return an overview of \u0645\u0646\u0635\u0629 \u0627\u0644\u0637\u0627\u0644\u0628 \u0627\u0644\u0639\u0628\u0642\u0631\u064A: name, target stages (\u0627\u0628\u062A\u062F\u0627\u0626\u064A/\u0645\u062A\u0648\u0633\u0637), and main features.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      name: "\u0645\u0646\u0635\u0629 \u0627\u0644\u0637\u0627\u0644\u0628 \u0627\u0644\u0639\u0628\u0642\u0631\u064A",
      tagline: "\u0627\u0644\u0645\u0646\u0635\u0629 \u0627\u0644\u062A\u0639\u0644\u064A\u0645\u064A\u0629 \u0627\u0644\u0634\u0627\u0645\u0644\u0629 \u0644\u0644\u0645\u0631\u062D\u0644\u062A\u064A\u0646 \u0627\u0644\u0627\u0628\u062A\u062F\u0627\u0626\u064A\u0629 \u0648\u0627\u0644\u0645\u062A\u0648\u0633\u0637\u0629",
      stages: ["\u0627\u0628\u062A\u062F\u0627\u0626\u064A", "\u0645\u062A\u0648\u0633\u0637"],
      features: [
        "\u0634\u0631\u0648\u062D\u0627\u062A \u0648\u0645\u0644\u062E\u0635\u0627\u062A \u0630\u0643\u064A\u0629",
        "\u0627\u062E\u062A\u0628\u0627\u0631\u0627\u062A \u062A\u0641\u0627\u0639\u0644\u064A\u0629 \u0648\u062A\u0635\u062D\u064A\u062D \u0641\u0648\u0631\u064A",
        "\u062D\u0644 \u0645\u0633\u0627\u0626\u0644 \u0627\u0644\u0643\u062A\u0627\u0628 \u0628\u0627\u0644\u0643\u0627\u0645\u064A\u0631\u0627",
        "\u0623\u0644\u0639\u0627\u0628 \u0627\u0644\u0639\u0628\u0627\u0642\u0631\u0629 \u0648\u062A\u062D\u062F\u064A\u0627\u062A \u0634\u0628\u0643\u0629 \u062E\u0644\u0627\u064A\u0627 \u0627\u0644\u0646\u062D\u0644",
        "\u0642\u0627\u0639\u0629 \u0627\u0644\u0639\u0628\u0627\u0642\u0631\u0629 \u0648\u062A\u062A\u0628\u0639 \u0627\u0644\u0646\u0642\u0627\u0637"
      ]
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/list-subscription-plans.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/payment-config.ts
var PLAN_PRICES = {
  semester: { price: 30, label: "\u0627\u0634\u062A\u0631\u0627\u0643 \u0641\u0635\u0644 \u062F\u0631\u0627\u0633\u064A \u0648\u0627\u062D\u062F", period: "\u0644\u0644\u0641\u0635\u0644 \u0627\u0644\u0648\u0627\u062D\u062F" },
  yearly: { price: 50, label: "\u0627\u0634\u062A\u0631\u0627\u0643 \u0633\u0646\u0629 \u0643\u0627\u0645\u0644\u0629 - \u0639\u0631\u0636 \u062E\u0627\u0635", period: "\u0633\u0646\u0648\u064A\u0627\u064B" }
};

// src/lib/mcp/tools/list-subscription-plans.ts
var list_subscription_plans_default = defineTool2({
  name: "list_subscription_plans",
  title: "List subscription plans",
  description: "Return the available subscription plans for \u0645\u0646\u0635\u0629 \u0627\u0644\u0637\u0627\u0644\u0628 \u0627\u0644\u0639\u0628\u0642\u0631\u064A with price in SAR and duration.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const plans = Object.entries(PLAN_PRICES).map(([id, p]) => ({
      id,
      label: p.label,
      price_sar: p.price,
      period: p.period
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(plans, null, 2) }],
      structuredContent: { plans }
    };
  }
});

// src/lib/mcp/index.ts
var SUPABASE_ISSUER = "https://kjubpaflsffnioixbfec.supabase.co/auth/v1";
var mcp_default = defineMcp({
  name: "genius-student-mcp",
  title: "\u0645\u0646\u0635\u0629 \u0627\u0644\u0637\u0627\u0644\u0628 \u0627\u0644\u0639\u0628\u0642\u0631\u064A MCP",
  version: "0.1.0",
  instructions: "Tools for \u0645\u0646\u0635\u0629 \u0627\u0644\u0637\u0627\u0644\u0628 \u0627\u0644\u0639\u0628\u0642\u0631\u064A, the Arabic learning platform for primary and middle school students. Use `get_platform_info` for a platform overview, and `list_subscription_plans` to fetch available plans and pricing in SAR.",
  auth: auth.oauth.issuer({
    issuer: SUPABASE_ISSUER,
    acceptedAudiences: ["authenticated"],
    resourceName: "\u0645\u0646\u0635\u0629 \u0627\u0644\u0637\u0627\u0644\u0628 \u0627\u0644\u0639\u0628\u0642\u0631\u064A MCP"
  }),
  tools: [get_platform_info_default, list_subscription_plans_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
